"""Initial migration with user role field

Revision ID: c99be3158653
Revises: 
Create Date: 2025-04-10 02:49:41.485327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99be3158653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed - we removed drop column commands that were causing errors
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed - we removed add column commands that were causing errors
    pass
    # ### end Alembic commands ###
